server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
